
export default {
  SIGNIANT_API_URL: import.meta.env.VITE_SIGNIANT_API_URL || 'https://api.signiant.com',
  SIGNIANT_CLIENT_ID: import.meta.env.VITE_SIGNIANT_CLIENT_ID,
  SIGNIANT_CLIENT_SECRET: import.meta.env.VITE_SIGNIANT_CLIENT_SECRET,
  SUPABASE_URL: import.meta.env.VITE_SUPABASE_URL,
  SUPABASE_ANON_KEY: import.meta.env.VITE_SUPABASE_ANON_KEY,
  SUPABASE_SERVICE_ROLE_KEY: import.meta.env.VITE_SUPABASE_SERVICE_ROLE_KEY
};
